UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Zadatak Grupa 1 - rešenja.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa1-filmovi-resenja.sql';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Zadatak Grupa 1 - rešenja.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa1-filmovi-resenja.sql';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Zadatak 24.11.2020. Grupa 1.pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa1-filmovi.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Zadatak 24.11.2020. Grupa 1.pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa1-filmovi.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Zadatak Grupa 3 filmovi - rešenja.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa3-filmovi-resenja.sql';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Zadatak Grupa 3 filmovi - rešenja.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa3-filmovi-resenja.sql';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Zadatak 24.11.2020. Grupa 3.pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa3-filmovi.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Zadatak 24.11.2020. Grupa 3.pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa3-filmovi.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Insert skript - vozači.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa3-vozaci-insert-vozaci.sql';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Insert skript - vozači.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa3-vozaci-insert-vozaci.sql';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Vozači - rešenja.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa3-vozaci-resenja.sql';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Vozači - rešenja.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa3-vozaci-resenja.sql';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Zadatak 24.11.2020. Grupa 3 (sema vozac).pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa3-vozaci.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Zadatak 24.11.2020. Grupa 3 (sema vozac).pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa3-vozaci.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Priprema 4 - rešenja.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa4-sobe-priprema4.sql';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Priprema 4 - rešenja.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa4-sobe-priprema4.sql';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Zadatak 27.11.2020. Grupa 5.pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa4-sobe.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Zadatak 27.11.2020. Grupa 5.pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-grupa4-sobe.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Insert skript - priprema.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-priprema-sa-vezbi-insert-priprema.sql';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Insert skript - priprema.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-priprema-sa-vezbi-insert-priprema.sql';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Priprema - rešenja.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-priprema-sa-vezbi-resenja.sql';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Priprema - rešenja.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-priprema-sa-vezbi-resenja.sql';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/SQL priprema.pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-priprema-sa-vezbi.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/SQL priprema.pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-priprema-sa-vezbi.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Zadaci sa vežbi - rešenja.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-zadaci-sa-vezbi-resenja.sql';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Zadaci sa vežbi - rešenja.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-zadaci-sa-vezbi-resenja.sql';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Zadaci sa vezbi (Randomized).pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-zadaci-sa-vezbi.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Zadaci sa vezbi (Randomized).pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-k1-zadaci-sa-vezbi.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/SQL cheatsheet.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-sql-cheatsheet.sql';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/SQL cheatsheet.sql' WHERE url = '/api/file/baze-podataka-1/K1/bp1-sql-cheatsheet.sql';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/SQL komande.pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-sql-komande.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/SQL komande.pdf' WHERE url = '/api/file/baze-podataka-1/K1/bp1-sql-komande.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K1/Insert skript - filmovi.sql' WHERE url = '/api/file/baze-podataka-1/K1/insert-filmovi.sql';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K1/Insert skript - filmovi.sql' WHERE url = '/api/file/baze-podataka-1/K1/insert-filmovi.sql';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER zbirka.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-er-zbirka.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER zbirka.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-er-zbirka.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER probni test Formula 1.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-formula1.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER probni test Formula 1.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-formula1.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER G2 fabrika - rešenje.jpeg' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g2-fabrika-resenje-1.jpeg';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER G2 fabrika - rešenje.jpeg' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g2-fabrika-resenje-1.jpeg';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER probni test G2 - Fabrika za preradu žitarica.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g2-fabrika.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER probni test G2 - Fabrika za preradu žitarica.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g2-fabrika.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER probni test G4 - Telekomunikacione kompanije.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g4-telekom.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER probni test G4 - Telekomunikacione kompanije.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g4-telekom.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER G5 autoškola - rešenje.jpg' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g5-autoskola-resenje-1.jpg';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER G5 autoškola - rešenje.jpg' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g5-autoskola-resenje-1.jpg';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER probni test G5 - Autoškola.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g5-autoskola.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER probni test G5 - Autoškola.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g5-autoskola.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER G7 IT firma - rešenje 1.jpg' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g7-it-firma-resenje-1.jpg';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER G7 IT firma - rešenje 1.jpg' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g7-it-firma-resenje-1.jpg';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER G7 IT firma - rešenje 2.jpg' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g7-it-firma-resenje-2.jpg';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER G7 IT firma - rešenje 2.jpg' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g7-it-firma-resenje-2.jpg';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER G7 IT firma - rešenje 3.jpeg' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g7-it-firma-resenje-3.jpeg';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER G7 IT firma - rešenje 3.jpeg' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g7-it-firma-resenje-3.jpeg';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER probni test G7 - IT firma.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g7-it-firma.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER probni test G7 - IT firma.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-g7-it-firma.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER probni test Mesna industrija.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-mesna-industrija.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER probni test Mesna industrija.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-mesna-industrija.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER probni test PSI G3 - Telekom.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-psi-g3-telekom.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER probni test PSI G3 - Telekom.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-psi-g3-telekom.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER probni test PSI G4 - Servis za slušanje muzike.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-psi-g4-muzika.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER probni test PSI G4 - Servis za slušanje muzike.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-er-psi-g4-muzika.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER Avio kompanija (urađeno).pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-avio.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER Avio kompanija (urađeno).pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-avio.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/Računarske vežbe ER.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-er.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/Računarske vežbe ER.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-er.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER Proizvodna organizacija (urađeno).pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-proizvodna.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER Proizvodna organizacija (urađeno).pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-proizvodna.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER zadatak 1.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-1.png';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER zadatak 1.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-1.png';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER zadatak 10.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-10.png';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER zadatak 10.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-10.png';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER zadatak 2.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-2.png';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER zadatak 2.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-2.png';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER zadatak 3.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-3.png';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER zadatak 3.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-3.png';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER zadatak 4.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-4.png';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER zadatak 4.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-4.png';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER zadatak 5.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-5.png';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER zadatak 5.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-5.png';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER zadatak 6.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-6.png';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER zadatak 6.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-6.png';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER zadatak 7.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-7.png';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER zadatak 7.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-7.png';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER zadatak 8.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-8.png';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER zadatak 8.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-8.png';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER zadatak 9.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-9.png';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER zadatak 9.png' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci-zadatak-9.png';
UPDATE materials SET url = '/api/file/baze-podataka-1/K2/ER zadaci sa vežbi.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K2/ER zadaci sa vežbi.pdf' WHERE url = '/api/file/baze-podataka-1/K2/bp1-k2-vezbe-zadaci.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K3-K4/Sekvencijalna datoteka.pdf' WHERE url = '/api/file/baze-podataka-1/K3-K4/bp1-k34-sekvencijalna-datoteka.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K3-K4/Sekvencijalna datoteka.pdf' WHERE url = '/api/file/baze-podataka-1/K3-K4/bp1-k34-sekvencijalna-datoteka.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K3-K4/Serijska datoteka.pdf' WHERE url = '/api/file/baze-podataka-1/K3-K4/bp1-k34-serijska-datoteka.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K3-K4/Serijska datoteka.pdf' WHERE url = '/api/file/baze-podataka-1/K3-K4/bp1-k34-serijska-datoteka.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K3-K4/Ulasci na stadion.csv' WHERE url = '/api/file/baze-podataka-1/K3-K4/bp1-k34-ulasci-na-stadion.csv';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K3-K4/Ulasci na stadion.csv' WHERE url = '/api/file/baze-podataka-1/K3-K4/bp1-k34-ulasci-na-stadion.csv';
UPDATE materials SET url = '/api/file/baze-podataka-1/K3-K4/Uvod u C.pdf' WHERE url = '/api/file/baze-podataka-1/K3-K4/bp1-k34-uvod-u-c.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K3-K4/Uvod u C.pdf' WHERE url = '/api/file/baze-podataka-1/K3-K4/bp1-k34-uvod-u-c.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/K3-K4/Zadaci - serijska i sekvencijalna datoteka.pdf' WHERE url = '/api/file/baze-podataka-1/K3-K4/bp1-k34-zadaci.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/K3-K4/Zadaci - serijska i sekvencijalna datoteka.pdf' WHERE url = '/api/file/baze-podataka-1/K3-K4/bp1-k34-zadaci.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/Teorija/Datoteke - prezentacija.pdf' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-datoteke-prezentacija.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/Teorija/Datoteke - prezentacija.pdf' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-datoteke-prezentacija.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/Teorija/Odgovori.txt' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-odgovori.txt';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/Teorija/Odgovori.txt' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-odgovori.txt';
UPDATE materials SET url = '/api/file/baze-podataka-1/Teorija/PSI odgovori.txt' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-psi-odgovori.txt';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/Teorija/PSI odgovori.txt' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-psi-odgovori.txt';
UPDATE materials SET url = '/api/file/baze-podataka-1/Teorija/PZ1 E2 online.pdf' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-pz1-e2-online.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/Teorija/PZ1 E2 online.pdf' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-pz1-e2-online.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/Teorija/PZ1 E2 online 2.pdf' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-pz1-e2-online2.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/Teorija/PZ1 E2 online 2.pdf' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-pz1-e2-online2.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/Teorija/PZ1 PSI online.pdf' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-pz1-psi-online.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/Teorija/PZ1 PSI online.pdf' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-pz1-psi-online.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/Teorija/PZ2 2020.pdf' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-pz2-2020.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/Teorija/PZ2 2020.pdf' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-pz2-2020.pdf';
UPDATE materials SET url = '/api/file/baze-podataka-1/Teorija/PZ2 PSI online.pdf' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-pz2-psi-online.pdf';
UPDATE material_assets SET url = '/api/file/baze-podataka-1/Teorija/PZ2 PSI online.pdf' WHERE url = '/api/file/baze-podataka-1/Teorija/bp1-pz2-psi-online.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/ispit/Pitanja koja su uvek dolazila.txt' WHERE url = '/api/file/programski-prevodioci/Ispit/pp-pitanja-koja-su-uvek-dolazila.txt';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/ispit/Pitanja koja su uvek dolazila.txt' WHERE url = '/api/file/programski-prevodioci/Ispit/pp-pitanja-koja-su-uvek-dolazila.txt';
UPDATE materials SET url = '/api/file/programski-prevodioci/ispit/Andjela skripta.pdf' WHERE url = '/api/file/programski-prevodioci/Ispit/pp-skripta-andjela.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/ispit/Andjela skripta.pdf' WHERE url = '/api/file/programski-prevodioci/Ispit/pp-skripta-andjela.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/ispit/Kucana skripta sa primerima.pdf' WHERE url = '/api/file/programski-prevodioci/Ispit/pp-skripta-sa-primerima.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/ispit/Kucana skripta sa primerima.pdf' WHERE url = '/api/file/programski-prevodioci/Ispit/pp-skripta-sa-primerima.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/00 1 Info.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-00-info.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/00 1 Info.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-00-info.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/01 1 Uvod.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-01-uvod.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/01 1 Uvod.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-01-uvod.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/02 1 Osnovne faze.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-02-1-osnovne-faze.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/02 1 Osnovne faze.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-02-1-osnovne-faze.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/02 2 Leksička analiza.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-02-2-leksicka-analiza.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/02 2 Leksička analiza.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-02-2-leksicka-analiza.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/03 1 Leksička analiza.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-03-1-leksicka-analiza.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/03 1 Leksička analiza.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-03-1-leksicka-analiza.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/03 2 Sintaksna analiza.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-03-2-sintaksna-analiza.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/03 2 Sintaksna analiza.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-03-2-sintaksna-analiza.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/04 1 Formalni jezici i automati.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-04-1-formalni-jezici-i-automati.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/04 1 Formalni jezici i automati.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-04-1-formalni-jezici-i-automati.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/05 1 Minic i micko.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-05-1-minic-i-micko.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/05 1 Minic i micko.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-05-1-minic-i-micko.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/05 2 Sintaksna stabla.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-05-2-sintaksna-stabla.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/05 2 Sintaksna stabla.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-05-2-sintaksna-stabla.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/05 3 Dvosmislenost.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-05-3-dvosmislenost.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/05 3 Dvosmislenost.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-05-3-dvosmislenost.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/06 1 Semantička analiza.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-06-1-semanticka-analiza.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/06 1 Semantička analiza.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-06-1-semanticka-analiza.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/06 2 Obrada grešaka.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-06-2-obrada-gresaka.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/06 2 Obrada grešaka.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-06-2-obrada-gresaka.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/07 1 GK uvod.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-07-1-gk-uvod.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/07 1 GK uvod.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-07-1-gk-uvod.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/07 2 GK micko uvod.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-07-2-gk-micko-uvod.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/07 2 GK micko uvod.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-07-2-gk-micko-uvod.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/08 1 GK micko impl.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-08-1-gk-micko-impl.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/08 1 GK micko impl.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-08-1-gk-micko-impl.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/08 2 GK micko izvrsavanje.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-08-2-gk-micko-izvrsavanje.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/08 2 GK micko izvrsavanje.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-08-2-gk-micko-izvrsavanje.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/09 1 medjukod.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-09-1-medjukod.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/09 1 medjukod.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-09-1-medjukod.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/09 2 optimizacije.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-09-2-optimizacije.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/09 2 optimizacije.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-09-2-optimizacije.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/10 1 optimizacije.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-10-1-optimizacije.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/10 1 optimizacije.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-10-1-optimizacije.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/11 1 jvm.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-11-1-jvm.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/11 1 jvm.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-11-1-jvm.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/11 2 jvm.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-11-2-jvm.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/11 2 jvm.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-11-2-jvm.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/12 1 jit i gc.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-12-1-jit-i-gc.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/12 1 jit i gc.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-12-1-jit-i-gc.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/13 1 tipovi.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-13-1-tipovi.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/13 1 tipovi.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-13-1-tipovi.pdf';
UPDATE materials SET url = '/api/file/programski-prevodioci/predavanja/14 Ispit.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-14-ispit.pdf';
UPDATE material_assets SET url = '/api/file/programski-prevodioci/predavanja/14 Ispit.pdf' WHERE url = '/api/file/programski-prevodioci/Prezentacije/pp-14-ispit.pdf';
UPDATE subjects SET professors = '["Slavica Kordić"]' WHERE id = 'baze-podataka-1';
