UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v3-adagrad.txt' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/ADAGRAD.py';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v3-adam.txt' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/ADAM.py';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-objasnjenje.txt' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/Objašnjenje rešavanja.txt';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v3-rms.txt' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/RMS.py';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v3-resenje.html' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/V3 Rešenje.html';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v3-uvod.html' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/V3 Uvod u neuronske mreže.html';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v3-zadatak.png' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/V3 Zadatak.png';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v4-tsp.html' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/V4 Genetski algoritam, TSP.html';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v4-ga.html' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/V4 Genetski algoritam.html';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v4-jss.html' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/V4 JSS.html';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v4-resenje.txt' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/V4 Rešenje.py';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v4-zadaci.pdf' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/V4 Zadaci.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v5-resenje.py' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/V5 Rešenje.py';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v5-zadaci.pdf' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/V5 Zadaci.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-v3-vezbe-pdf.pdf' WHERE url = '/api/file/metode-optimizacije/Računarske vežbe/Veštačke neuronske mreže.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarski-kolokvijum/mo-python-mo1.txt' WHERE url = '/api/file/metode-optimizacije/Računarski kolokvijum/Python podsetnik MO1.txt';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarski-kolokvijum/mo-python-podsetnik.txt' WHERE url = '/api/file/metode-optimizacije/Računarski kolokvijum/Python podsetnik.txt';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarski-kolokvijum/mo-rk-2023-2024.pdf' WHERE url = '/api/file/metode-optimizacije/Računarski kolokvijum/Računarski kolokvijum 2023-2024.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarski-kolokvijum/mo-rk-starije.pdf' WHERE url = '/api/file/metode-optimizacije/Računarski kolokvijum/Računarski kolokvijum, starije godine.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/rokovi/mo-rok-2023-02.pdf' WHERE url = '/api/file/metode-optimizacije/Rokovi/Februarski rok 2023, K1+K2.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/rokovi/mo-rokovi.pdf' WHERE url = '/api/file/metode-optimizacije/Rokovi/Ispitni rokovi.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/rokovi/mo-rok-2024-07-k1.pdf' WHERE url = '/api/file/metode-optimizacije/Rokovi/Junsko-julski rok 2024, K1.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/teorija/mo-ispitna-pitanja.pdf' WHERE url = '/api/file/metode-optimizacije/Teorija/Ispitna pitanja.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/teorija/mo-pitanja-246.pdf' WHERE url = '/api/file/metode-optimizacije/Teorija/Pitanja 2, 4 i 6.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/teorija/mo-skripta.pdf' WHERE url = '/api/file/metode-optimizacije/Teorija/Skripta.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-vezbe-gradijentne.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/Gradijentne višedimenzione metode - zadaci.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v1.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V1 Jednodimenzionalna optimizacija.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v10.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V10 Jednodimenzione numeričke metode.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v11.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V11 Diferencijalne jednačine.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v12.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V12 Uvod u dinamičku optimizaciju.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v13.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V13 Prirodno granični uslovi i Bolca problem.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v14.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V14 Asinhrono variranje. Izoperimetrijski problem.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v15.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V15 Optimalno upravljanje.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v16.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V16 Nespecificirani vremenski interval. Bolca problem.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v17.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V17 Priprema za kolokvijum2.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v2.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V2 Visedimenzionalna optimizacija bez ogranicenja.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v3.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V3 Metod smene i ograničene varijacije.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v4.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V4 Optimizacija uz ograničenja tipa jednakosti. Metod Lagranževih množitelja i metod kazenih funkcija.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v5.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V5 Optimizacija uz ograničenja tipa nejednakosti. Metod smene, ograničene varijacije i Lagranževih množitelja.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v6.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V6 Karuš, Kun - Takerovi uslovi.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v7.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V7 Simpleks - linearno programiranje.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v8.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V8 Metod najmanjih kvadrata.pdf';
UPDATE materials SET url = '/api/file/metode-optimizacije/vezbe/mo-v9.pdf' WHERE url = '/api/file/metode-optimizacije/Vežbe/V9 Priprema za kolokvijum1.pdf';
