INSERT OR IGNORE INTO subjects (id, name, semester, espb, elective, elective_group, description, professors, assistants)
VALUES ('veb-programiranje', 'Veb programiranje', 6, 6, 0, NULL, 'HTTP protokol, serveri, JSP, servlet tehnologije.', '["Milan Vidaković"]', '["Bojana Ivanović Mijatov", "Glorija-Katarina Grujić", "Tatjana Gavrilović"]');

INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-predavanja-html', 'veb-programiranje', 'Predavanja 1, HTML primeri', 'theory', NULL, NULL, 'html', '/api/file/web/predavanja/predavanja-html/index.html', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-predavanja-css', 'veb-programiranje', 'Predavanja 2, CSS primeri', 'theory', NULL, NULL, 'html', '/api/file/web/predavanja/predavanja-css/index.html', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-predavanja-html5', 'veb-programiranje', 'Predavanja 2, HTML5 primeri', 'theory', NULL, NULL, 'html', '/api/file/web/predavanja/predavanja-html5/index.html', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-vezbe', 'veb-programiranje', 'Vežbe', 'problems', NULL, NULL, 'html', '/api/file/web/vezbe/index.html', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-ispit', 'veb-programiranje', 'Web ispit', 'theory', NULL, NULL, 'text', '/api/file/web/ispit/web-ispit.txt', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-teorija', 'veb-programiranje', 'Teorija WEB', 'exam', NULL, NULL, 'pdf', '/api/file/web/ispit/web-teorija.pdf', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-usmeni', 'veb-programiranje', 'Web usmeni', 'theory', NULL, NULL, 'pdf', '/api/file/web/ispit/web-usmeni.pdf', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-test', 'veb-programiranje', 'Test iz WEB programiranja', 'exam', NULL, NULL, 'text', '/api/file/web/ispit/web-test.txt', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-pitanja-odgovori', 'veb-programiranje', 'Pitanja i odgovori', 'exam', NULL, NULL, 'text', '/api/file/web/ispit/web-pitanja-odgovori.md', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-ispitna-pitanja', 'veb-programiranje', 'Web ispitna pitanja', 'exam', NULL, NULL, 'text', '/api/file/web/ispit/web-ispitna-pitanja.md', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-skripta', 'veb-programiranje', 'WEB skripta', 'misc', NULL, NULL, 'pdf', '/api/file/web/ispit/web-skripta.pdf', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-predavanja-java', 'veb-programiranje', 'Java', 'theory', NULL, NULL, 'text', '/api/file/web/predavanja/web-predavanja-java.txt', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-predavanja-http', 'veb-programiranje', 'HTTP protokol', 'theory', NULL, NULL, 'text', '/api/file/web/predavanja/web-predavanja-http.txt', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-predavanja-servleti', 'veb-programiranje', 'Servleti', 'theory', NULL, NULL, 'text', '/api/file/web/predavanja/web-predavanja-servleti.txt', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-predavanja-p07', 'veb-programiranje', 'P07', 'theory', NULL, NULL, 'text', '/api/file/web/predavanja/web-predavanja-p07.txt', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-predavanja-p08', 'veb-programiranje', 'P08', 'theory', NULL, NULL, 'text', '/api/file/web/predavanja/web-predavanja-p08.txt', 0, '[]', 1);
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable) VALUES ('web-predavanja-p09', 'veb-programiranje', 'P09', 'theory', NULL, NULL, 'text', '/api/file/web/predavanja/web-predavanja-p09.txt', 0, '[]', 1);
