ALTER TABLE materials ADD COLUMN description TEXT NOT NULL DEFAULT '';
UPDATE materials SET title = '00 Informacije o predmetu' WHERE id = 'pp-00-info';
UPDATE materials SET title = '01 Uvod' WHERE id = 'pp-01-uvod';
UPDATE materials SET title = '02-1 Osnovne faze' WHERE id = 'pp-02-1-osnovne-faze';
UPDATE materials SET title = '02-2 Leksička analiza' WHERE id = 'pp-02-2-leksicka-analiza';
UPDATE materials SET title = '03-1 Leksička analiza' WHERE id = 'pp-03-1-leksicka-analiza';
UPDATE materials SET title = '03-2 Sintaksna analiza' WHERE id = 'pp-03-2-sintaksna-analiza';
UPDATE materials SET title = '04 Formalni jezici i automati' WHERE id = 'pp-04-1-formalni-jezici-i-automati';
UPDATE materials SET title = '05-1 MiniC i Micko' WHERE id = 'pp-05-1-minic-i-micko';
UPDATE materials SET title = '05-2 Sintaksna stabla' WHERE id = 'pp-05-2-sintaksna-stabla';
UPDATE materials SET title = '05-3 Dvosmislenost' WHERE id = 'pp-05-3-dvosmislenost';
UPDATE materials SET title = '06-1 Semantička analiza' WHERE id = 'pp-06-1-semanticka-analiza';
UPDATE materials SET title = '06-2 Obrada grešaka' WHERE id = 'pp-06-2-obrada-gresaka';
UPDATE materials SET title = '07-1 GK uvod' WHERE id = 'pp-07-1-gk-uvod';
UPDATE materials SET title = '07-2 GK Micko uvod' WHERE id = 'pp-07-2-gk-micko-uvod';
UPDATE materials SET title = '08-1 GK Micko implementacija' WHERE id = 'pp-08-1-gk-micko-impl';
UPDATE materials SET title = '08-2 GK Micko izvršavanje' WHERE id = 'pp-08-2-gk-micko-izvrsavanje';
UPDATE materials SET title = '09-1 Međukod' WHERE id = 'pp-09-1-medjukod';
UPDATE materials SET title = '09-2 Optimizacije' WHERE id = 'pp-09-2-optimizacije';
UPDATE materials SET title = '10 Optimizacije' WHERE id = 'pp-10-1-optimizacije';
UPDATE materials SET title = '11-1 JVM' WHERE id = 'pp-11-1-jvm';
UPDATE materials SET title = '11-2 JVM' WHERE id = 'pp-11-2-jvm';
UPDATE materials SET title = '12-1 JIT i GC' WHERE id = 'pp-12-1-jit-i-gc';
UPDATE materials SET title = '13 Tipovi' WHERE id = 'pp-13-1-tipovi';
UPDATE materials SET title = '14 Priprema za ispit' WHERE id = 'pp-14-ispit';
UPDATE materials SET title = 'V1 Uvod u Python, nastavak' WHERE id = 'nans-v1-beleska';
UPDATE materials SET title = 'V2 Uvod u linearnu regresiju (rešenje)' WHERE id = 'nans-v2-resenje';
UPDATE materials SET title = 'V2 Uvod u linearnu regresiju (zadatak)' WHERE id = 'nans-v2-zadatak';
UPDATE materials SET title = 'V3 Zaključivanje o modelu (rešenje)' WHERE id = 'nans-v3-resenje';
UPDATE materials SET title = 'V3 Zaključivanje o modelu (zadatak)' WHERE id = 'nans-v3-zadatak';
UPDATE materials SET title = 'V4 L.I.N.E. pretpostavke (rešenje)' WHERE id = 'nans-v4-resenje';
UPDATE materials SET title = 'V4 L.I.N.E. pretpostavke (zadatak)' WHERE id = 'nans-v4-zadatak';
UPDATE materials SET title = 'V5 Višestruka linearna regresija (rešenje)' WHERE id = 'nans-v5-resenje';
UPDATE materials SET title = 'V5 Višestruka linearna regresija (zadatak)' WHERE id = 'nans-v5-zadatak';
UPDATE materials SET title = 'V6 Nedostajuće vrednosti (rešenje)' WHERE id = 'nans-v6-resenje';
UPDATE materials SET title = 'V6 Nedostajuće vrednosti (zadatak)' WHERE id = 'nans-v6-zadatak';
UPDATE materials SET title = 'V7 Priprema za kolokvijum 1 (rešenje)' WHERE id = 'nans-v7-resenje';
UPDATE materials SET title = 'V7 Priprema za kolokvijum 1 (zadatak)' WHERE id = 'nans-v7-zadatak';
UPDATE materials SET title = 'V2 linreg_simple (rešenje)' WHERE id = 'nans-v2-linreg_simple-resenje';
UPDATE materials SET title = 'V2 todo3 (rešenje)' WHERE id = 'nans-v2-todo3-resenje';
UPDATE materials SET title = 'V2 todo4 (rešenje)' WHERE id = 'nans-v2-todo4-resenje';
UPDATE materials SET title = 'V2 linreg_simple (zadatak)' WHERE id = 'nans-v2-linreg_simple';
UPDATE materials SET title = 'V2 todo3 (zadatak)' WHERE id = 'nans-v2-todo3';
UPDATE materials SET title = 'V2 todo4 (zadatak)' WHERE id = 'nans-v2-todo4';
UPDATE materials SET title = 'V3 line_pretpostavke (rešenje)' WHERE id = 'nans-v3-line_pretpostavke-resenje';
UPDATE materials SET title = 'V3 todo1 (rešenje)' WHERE id = 'nans-v3-todo1-resenje';
UPDATE materials SET title = 'V3 todo2 (rešenje)' WHERE id = 'nans-v3-todo2-resenje';
UPDATE materials SET title = 'V3 line_pretpostavke (zadatak)' WHERE id = 'nans-v3-line_pretpostavke';
UPDATE materials SET title = 'V3 todo1 (zadatak)' WHERE id = 'nans-v3-todo1';
UPDATE materials SET title = 'V3 todo2 (zadatak)' WHERE id = 'nans-v3-todo2';
UPDATE materials SET title = 'V4 line_pretpostavke (rešenje)' WHERE id = 'nans-v4-line_pretpostavke-resenje';
UPDATE materials SET title = 'V4 todo1 (rešenje)' WHERE id = 'nans-v4-todo1-resenje';
UPDATE materials SET title = 'V4 todo2 (rešenje)' WHERE id = 'nans-v4-todo2-resenje';
UPDATE materials SET title = 'V4 todo3 (rešenje)' WHERE id = 'nans-v4-todo3-resenje';
UPDATE materials SET title = 'V4 line_pretpostavke (zadatak)' WHERE id = 'nans-v4-line_pretpostavke';
UPDATE materials SET title = 'V4 todo1 (zadatak)' WHERE id = 'nans-v4-todo1';
UPDATE materials SET title = 'V4 todo2 (zadatak)' WHERE id = 'nans-v4-todo2';
UPDATE materials SET title = 'V4 todo3 (zadatak)' WHERE id = 'nans-v4-todo3';
UPDATE materials SET title = 'V5 line_pretpostavke (rešenje)' WHERE id = 'nans-v5-line_pretpostavke-resenje';
UPDATE materials SET title = 'V5 todo1 (rešenje)' WHERE id = 'nans-v5-todo1-resenje';
UPDATE materials SET title = 'V5 todo2 (rešenje)' WHERE id = 'nans-v5-todo2-resenje';
UPDATE materials SET title = 'V5 todo3 (rešenje)' WHERE id = 'nans-v5-todo3-resenje';
UPDATE materials SET title = 'V5 line_pretpostavke (zadatak)' WHERE id = 'nans-v5-line_pretpostavke';
UPDATE materials SET title = 'V5 todo1 (zadatak)' WHERE id = 'nans-v5-todo1';
UPDATE materials SET title = 'V5 todo2 (zadatak)' WHERE id = 'nans-v5-todo2';
UPDATE materials SET title = 'V5 todo3 (zadatak)' WHERE id = 'nans-v5-todo3';
UPDATE materials SET title = 'V6 todo1 (rešenje)' WHERE id = 'nans-v6-todo1-resenje';
UPDATE materials SET title = 'V6 utils (pomoćni kod)' WHERE id = 'nans-v6-utils';
UPDATE materials SET title = 'V6 todo1 (zadatak)' WHERE id = 'nans-v6-todo1';
UPDATE materials SET title = 'V6 utils (pomoćni kod)' WHERE id = 'nans-v6-utils-resenje';
UPDATE materials SET title = 'V7 resenje (rešenje)' WHERE id = 'nans-v7-resenje-resenje';
UPDATE materials SET title = 'V7 utils_nans1 (pomoćni kod)' WHERE id = 'nans-v7-utils_nans1';
UPDATE materials SET title = 'V0 Uvod u Python' WHERE id = 'nans-v0-uvod';
UPDATE materials SET title = 'V1 Uvod u Python, nastavak' WHERE id = 'nans-v1-nastavak';
UPDATE materials SET title = 'V1 Uvod u Python, nastavak 2' WHERE id = 'nans-v1-nastavak-2';
UPDATE materials SET title = 'V1 Uvod u Python, zadaci' WHERE id = 'nans-v1-zadaci';
UPDATE materials SET title = title || ' (kurs)' WHERE id = 'ori-kod-robot-board';
UPDATE materials SET title = title || ' (kurs)' WHERE id = 'ori-kod-robot-game';
UPDATE materials SET title = title || ' (kurs)' WHERE id = 'ori-kod-robot-search';
UPDATE materials SET title = title || ' (kurs)' WHERE id = 'ori-kod-robot-state';
UPDATE materials SET title = title || ' (kurs)' WHERE id = 'ori-kod-sah-board';
UPDATE materials SET title = title || ' (kurs)' WHERE id = 'ori-kod-sah-game';
UPDATE materials SET title = title || ' (kurs)' WHERE id = 'ori-kod-sah-pieces';
UPDATE materials SET title = title || ' (kurs)' WHERE id = 'ori-kod-sah-search';
UPDATE materials SET title = title || ' (kurs)' WHERE id = 'ori-kod-sah-state';
UPDATE materials SET title = title || ' (kurs)' WHERE id = 'ori-kod-lavirint-brain';
UPDATE materials SET title = title || ' (kurs)' WHERE id = 'ori-kod-lavirint-game';
UPDATE materials SET title = title || ' (kurs)' WHERE id = 'ori-kod-lavirint-env';
UPDATE materials SET title = 'V5 Rešenje, kod' WHERE id = 'mo-v5-resenje';
UPDATE materials SET title = 'JSP i servleti' WHERE id = 'web-predavanja-p07';
UPDATE materials SET title = 'JavaScript' WHERE id = 'web-predavanja-p08';
UPDATE materials SET title = 'jQuery' WHERE id = 'web-predavanja-p09';
DELETE FROM materials WHERE id = 'web-vezbe';
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable, description) VALUES ('web-vezba-citac', 'veb-programiranje', 'Vežba: Web čitač', 'problems', NULL, NULL, 'html', '/api/file/web/vezbe/zad1.html', 0, '[]', 1, '');
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable, description) VALUES ('web-vezba-tabele', 'veb-programiranje', 'Vežba: CSS tabele', 'problems', NULL, NULL, 'html', '/api/file/web/vezbe/zad2.html', 0, '[]', 1, '');
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable, description) VALUES ('web-vezba-registracija', 'veb-programiranje', 'Vežba: registracija', 'problems', NULL, NULL, 'html', '/api/file/web/vezbe/zad2b.html', 0, '[]', 1, '');
UPDATE materials SET description = 'Rokovi: 26.1.2019, 7.2.2019, 13.2.2020, 19.9.2020, 7.9.2024, 25.9.2024.' WHERE id = 'mo-rokovi';
UPDATE materials SET description = 'Rešeni računski kolokvijumi, 14 slika.' WHERE id = 'mo-rk-starije';
UPDATE materials SET description = 'Računarski kolokvijum 2023-2024, grupa B, 6 strana.' WHERE id = 'mo-rk-2023-2024';
UPDATE materials SET description = 'Rukopisna teorija, pitanja 2, 4 i 6, 11 strana.' WHERE id = 'mo-pitanja-246';
UPDATE materials SET description = 'Februarski rok 2023, kolokvijumi 1 i 2 na jednoj slici.' WHERE id = 'mo-rok-2023-02';
UPDATE materials SET description = 'Rukopisna skripta, 11 strana.' WHERE id = 'web-skripta';
UPDATE materials SET description = 'Zadaci za vežbu 4, grupe 2, 4, 5, 7 i 8.' WHERE id = 'mo-v4-zadaci';
UPDATE materials SET description = 'Zadaci za vežbu 5, grupe 1, 2, 7 i 8.' WHERE id = 'mo-v5-zadaci';
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable, description) VALUES ('bp1-vodic', 'baze-podataka-1', 'Vodič', 'theory', NULL, NULL, 'text', '/api/file/baze-podataka-1/vodic.txt', 0, '[]', 1, 'Snimljene vežbe i saveti za polaganje.');
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable, description) VALUES ('metode-vodic', 'metode-optimizacije', 'Vodič', 'theory', NULL, NULL, 'text', '/api/file/metode-optimizacije/vodic.txt', 0, '[]', 1, 'Snimljene vežbe i saveti za polaganje.');
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable, description) VALUES ('nans-vodic', 'numericki-algoritmi-i-numericki-softver', 'Vodič', 'theory', NULL, NULL, 'text', '/api/file/numericki-algoritmi-i-numericki-softver/vodic.txt', 0, '[]', 1, 'Snimljene vežbe i saveti za polaganje.');
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable, description) VALUES ('prevodioci-vodic', 'programski-prevodioci', 'Vodič', 'theory', NULL, NULL, 'text', '/api/file/programski-prevodioci/vodic.txt', 0, '[]', 1, 'Snimljene vežbe i saveti za polaganje.');
UPDATE materials SET title = 'V6 utils rešenja (pomoćni kod)' WHERE id = 'nans-v6-utils-resenje';
UPDATE materials SET title = 'V7 Rešenje' WHERE id = 'nans-v7-resenje';
