ALTER TABLE materials ADD COLUMN unit TEXT;
UPDATE materials SET unit = 'V0' WHERE id LIKE 'nans-v0-%';
UPDATE materials SET unit = 'V1' WHERE id LIKE 'nans-v1-%';
UPDATE materials SET unit = 'V2' WHERE id LIKE 'nans-v2-%';
UPDATE materials SET unit = 'V3' WHERE id LIKE 'nans-v3-%';
UPDATE materials SET unit = 'V4' WHERE id LIKE 'nans-v4-%';
UPDATE materials SET unit = 'V5' WHERE id LIKE 'nans-v5-%';
UPDATE materials SET unit = 'V6' WHERE id LIKE 'nans-v6-%';
UPDATE materials SET unit = 'V7' WHERE id LIKE 'nans-v7-%';
UPDATE materials SET unit = 'V3' WHERE id LIKE 'mo-v3-%';
UPDATE materials SET unit = 'V4' WHERE id LIKE 'mo-v4-%';
UPDATE materials SET unit = 'V5' WHERE id LIKE 'mo-v5-%';
UPDATE materials SET unit = 'V5' WHERE id IN ('ori-vezbe-v5-naivni-bajes', 'ori-v5-nb-py');
UPDATE materials SET unit = 'V7' WHERE id IN ('ori-vezbe-v7-karpathy', 'ori-v7-zadatak');
UPDATE materials SET unit = 'V8' WHERE id IN ('ori-vezbe-v8-konvolutivne', 'ori-v8-zadatak', 'ori-v8-resenje-py');
UPDATE materials SET unit = 'V9' WHERE id IN ('ori-vezbe-v9-rnn', 'ori-v9-zadatak');
UPDATE materials SET url = '/api/file/web/predavanja/web-predavanja-p07.md' WHERE id = 'web-predavanja-p07';
UPDATE materials SET url = '/api/file/web/predavanja/web-predavanja-p08.md' WHERE id = 'web-predavanja-p08';
UPDATE materials SET url = '/api/file/web/predavanja/web-predavanja-p09.md' WHERE id = 'web-predavanja-p09';
UPDATE materials SET url = '/api/file/ori/teorija/ORI.md' WHERE id = 'ori-beleske';
UPDATE materials SET url = '/api/file/metode-optimizacije/racunarske-vezbe/mo-objasnjenje.md' WHERE id = 'mo-objasnjenje';
UPDATE materials SET tags = '["Rokovi"]' WHERE id = 'mo-rokovi';
UPDATE materials SET tags = '["Starije godine"]' WHERE id = 'mo-rk-starije';
UPDATE materials SET tags = '["2023-2024"]' WHERE id = 'mo-rk-2023-2024';
UPDATE materials SET tags = '["Rukopis"]' WHERE id IN ('mo-pitanja-246', 'web-skripta');
DELETE FROM materials WHERE id = 'mo-rok-2023-02';
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable, description) VALUES ('mo-rok-2023-02-k1', 'metode-optimizacije', 'Februarski rok 2023, K1', 'exam', 'K1', NULL, 'pdf', '/api/file/metode-optimizacije/rokovi/mo-rok-2023-02.pdf', 1, '[]', 1, '');
INSERT OR IGNORE INTO materials (id, subject_id, title, category, exam_part, solved, file_type, url, page_count, tags, searchable, description) VALUES ('mo-rok-2023-02-k2', 'metode-optimizacije', 'Februarski rok 2023, K2', 'exam', 'K2', NULL, 'pdf', '/api/file/metode-optimizacije/rokovi/mo-rok-2023-02.pdf', 1, '[]', 1, '');
UPDATE materials SET title = 'V7 Rešenje' WHERE id = 'nans-v7-resenje';
UPDATE materials SET description = 'Skenirane slike, pretražuje se samo naslov.' WHERE id IN ('mo-rk-starije', 'mo-rk-2023-2024', 'mo-rok-2023-02-k1', 'mo-rok-2023-02-k2', 'mo-rok-2024-07-k1');
