name = "app"
main = "src/index.ts"
compatibility_date = "2026-06-05"

[[d1_databases]]
binding = "DB"
database_name = "index-db"
database_id = "dc88caa9-8d1a-4b10-b43a-6189a7aaf87a"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "index-bucket"

[assets]
directory = "../app/dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
