name = "app"
main = "src/index.ts"
compatibility_date = "2026-06-05"

[[d1_databases]]
binding = "DB"
database_name = "index-db"
database_id = "2d8c407f-f022-483d-9438-b4c64b5ab313"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "index-bucket"

[vars]
SESSION_SECRET = "change-me-to-a-real-secret"

[assets]
directory = "../app/dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
